# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]


jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: ./*
        remote_path: /home/ec2-user/test/deploy-dev/source/
        remote_host: "${{ secrets.AWS_HOST }}"
        remote_user: ec2-user
        remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
    - name: ec2 update
      uses: appleboy/ssh-action@master
      with:
          host: "${{ secrets.AWS_HOST }}"
          username: ec2-user
          key: "${{ secrets.SSH_PRIVATE_KEY }}"
          script: npm install && pm2 restart ecosystem.config.js --env development --only deploy-dev