# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: ./*
        remote_path: /home/ec2-user/test/deploy-dev/source/
        remote_host: "${{ secrets.AWS_HOST }}"
        remote_user: ec2-user
        remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
    - name: ec2 update
      uses: appleboy/ssh-action@master
      with:
          host: "${{ secrets.AWS_HOST }}"
          username: ec2-user
          key: "${{ secrets.SSH_PRIVATE_KEY }}"
          script: cd /home/ec2-user/test/deploy-dev/source && npm install && pm2 restart ecosystem.config.js --env development --only deploy-dev
    - name: send result to slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: WS-API develop Deploy # default: 8398a7@action-slack
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.